#!/usr/bin/perl -W
# $Id: makeenum,v 1.3 2003/06/05 14:39:54 bursa Exp $

$out = shift or die "usage: makeenum leafname";

open H, ">$out.h" or die "open 'enum.h' failed";
open C, ">$out.c" or die "open 'enum.c' failed";

print C "#include \"$out.h\"\n\n";

while (<>) {
    chomp;
    @enum = split;
    $name = shift @enum;
   
    @uc_enum = map uc, @enum;
    s/-/_/g foreach (@uc_enum);
    $uc_name = uc $name;
    
    print H "extern const char * const ${name}_name[];\n";
    print H "typedef enum {\n	${uc_name}_";
    print H join ",\n	${uc_name}_", @uc_enum;
    print H ",\n	${uc_name}_UNKNOWN\n";
    print H "} $name;\n";
    print H "$name ${name}_parse(const char * const s);\n\n";
    
    print C "/**\n * $name\n */\n\n";
    print C "const char * const ${name}_name[] = {\n	\"";
    print C join "\",\n	\"", @enum;
    print C "\"\n};\n\n";
    print C "$name ${name}_parse(const char * const s)\n{\n";
    foreach $x (@enum) {
        $ux = uc $x;
	$ux =~ s/-/_/g;
        print C "	if (strcasecmp(s, \"$x\") == 0) return ${uc_name}_$ux;\n";
    }
    print C "	return ${uc_name}_UNKNOWN;\n}\n\n";
}
