# Image content handler sources
include content/handlers/image/Makefile

S_IMAGE := $(addprefix content/handlers/image/,$(S_IMAGE))

# CSS sources
include content/handlers/css/Makefile

S_CONTENT += $(addprefix handlers/css/,$(S_CSS))

# Javascript source
include content/handlers/javascript/Makefile

S_CONTENT += $(addprefix handlers/javascript/,$(S_JAVASCRIPT))

INCLUDE_DIRS += content/handlers
