# Image content handler sources
include content/handlers/image/Makefile

S_IMAGE := $(addprefix content/handlers/image/,$(S_IMAGE))

# CSS sources
include content/handlers/css/Makefile

S_CSS := $(addprefix content/handlers/css/,$(S_CSS))

INCLUDE_DIRS += content/handlers
