# NetSurf Frontend sources

FRONTEND_SOURCE_DIR := frontends/$(TARGET)
FRONTEND_RESOURCES_DIR := frontends/$(TARGET)/res

# Target Specific setup
include frontends/$(TARGET)/Makefile

S_FRONTEND := $(addprefix frontends/$(TARGET)/,$(S_FRONTEND))

INCLUDE_DIRS += frontends
