#
# NetSurf build configuration
#
# Some of these options support an 'AUTO' option, as well as YES and NO.  If
# AUTO is available, the Makefile will attempt to detect if that feature is
# available when such is used.

# ----------------------------------------------------------------------------
# Options relating to all versions of NetSurf
# ----------------------------------------------------------------------------

# Enable NetSurf's built-in BMP support
# Valid options: YES, NO
NETSURF_USE_BMP := YES

# Enable NetSurf's built-in GIF support
# Valid options: YES, NO
NETSURF_USE_GIF := YES

# Enable NetSurf's use of IJG's libjpeg
# Valid options: YES, NO
NETSURF_USE_JPEG := YES

# Enable NetSurf's use of libmng for displaying MNGs and PNGs
# Valid options: YES, NO
NETSURF_USE_MNG := NO

# Enable NetSurf's use of libpng for displaying PNGs. If MNG and PNG
# are both enabled then NetSurf will choose libpng for PNGs, leaving
# MNGs and JNGs to libmng.
# Valid options: YES, NO
NETSURF_USE_PNG := YES

# Use libharu to enable PDF export and GTK printing support.  There is no
# auto-detection available for this, as it does not have a pkg-config file.
# Valid options: YES, NO
NETSURF_USE_HARU_PDF := YES

# Enable stripping the NetSurf binary
# Valid options: YES, NO
NETSURF_STRIP_BINARY := NO

# Template used for constructing the User Agent: string.  The first two
# replacements are major/minor version, second two are OS and architecture.
# Please don't be tempted to mention Mozilla here!  Let's let that lie die.
NETSURF_UA_FORMAT_STRING := "NetSurf/%d.%d (%s; %s)"

# Default home page if one is not defined.  Note that this does not apply to
# the RISC OS version, as it has its own local home page, and it can be changed
# by editing the end of gui_init2() in riscos/gui.c
NETSURF_HOMEPAGE := "http://www.netsurf-browser.org/welcome/"

# Force using glibc internal iconv implementation instead of external libiconv
# Valid options: YES, NO
NETSURF_USE_LIBICONV_PLUG := YES

# Initial CFLAGS. Optimisation level etc. tend to be target specific.
CFLAGS := 

# ----------------------------------------------------------------------------
# RISC OS-specific options
# ----------------------------------------------------------------------------
ifeq ($(TARGET),riscos)

  # Enable using Hubbub to parse HTML rather than libxml2
  # Valid options: YES, NO
  NETSURF_USE_HUBBUB := YES

  # Use James Bursa's libsvgtiny for rendering SVG images
  # Valid options: YES, NO
  NETSURF_USE_NSSVG := YES

  # Use pencil to enable export to Drawfile
  # Valid options: YES, NO
  NETSURF_USE_DRAW := YES

  # Enable NetSurf's RISC OS Sprite support via Tinct
  # Valid options: YES, NO
  NETSURF_USE_SPRITE := YES

  # Enable NetSurf's ArtWorks support via AWRender
  # Valid options: YES, NO
  NETSURF_USE_ARTWORKS := YES

  # Enable support for the Acorn plugin protocol
  # Valid options: YES, NO
  NETSURF_USE_PLUGINS := NO

  # Optimisation levels
  CFLAGS += -O -Wuninitialized

endif

# ----------------------------------------------------------------------------
# GTK-specific options
# ----------------------------------------------------------------------------
ifeq ($(TARGET),gtk)

  # Where to search for NetSurf's resources after looking in ~/.netsurf and
  # $NETSURFRES.  It must have a trailing /
  NETSURF_GTK_RESOURCES := /usr/local/share/netsurf/

  # Where to install the netsurf binary
  NETSURF_GTK_BIN := /usr/local/bin/

  # Enable using Hubbub to parse HTML rather than libxml2
  # Valid options: YES, NO, AUTO
  NETSURF_USE_HUBBUB := AUTO

  # Use librsvg in conjunction with Cairo to render SVG images
  # Valid options: YES, NO, AUTO
  NETSURF_USE_RSVG := AUTO

  # Use James Shaw's librosprite for rendering RISC OS Sprites
  # Valid options: YES, NO, AUTO
  NETSURF_USE_ROSPRITE := AUTO

  # Configuration overrides for Mac OS X
  ifeq ($(HOST),macosx)
    NETSURF_USE_LIBICONV_PLUG := NO
    NETSURF_USE_HARU_PDF := NO
  endif

  # Optimisation levels
  CFLAGS += -O2 -Wuninitialized

endif

# ----------------------------------------------------------------------------
# BeOS-specific options
# ----------------------------------------------------------------------------
ifeq ($(TARGET),beos)

  # Use James Shaw's librosprite for rendering RISC OS Sprites
  # Valid options: YES, NO, AUTO
  NETSURF_USE_ROSPRITE := AUTO

  # Use libharu to enable PDF export and GTK printing support.
  # Valid options: YES, NO
  NETSURF_USE_HARU_PDF := NO

  # Force using glibc internal iconv implementation instead of external libiconv
  # Valid options: YES, NO
  NETSURF_USE_LIBICONV_PLUG := NO

  # Optimisation levels
  CFLAGS += -O2 -Wuninitialized

endif

# ----------------------------------------------------------------------------
# Amiga-specific options
# ----------------------------------------------------------------------------
ifeq ($(TARGET),amiga)

  # Use James Shaw's librosprite for rendering RISC OS Sprites
  # Valid options: YES, NO, AUTO
  NETSURF_USE_ROSPRITE := YES

  # Enable using Hubbub to parse HTML rather than libxml2
  # Valid options: YES, NO, AUTO
  NETSURF_USE_HUBBUB := YES

  # Optimisation levels
  CFLAGS += -O2 -Wuninitialized

endif

# ----------------------------------------------------------------------------
# Debug-target-specific options
# ----------------------------------------------------------------------------
ifeq ($(TARGET),debug)
  # Optimisation levels
  CFLAGS += -O0
endif

# Include any local overrides
-include Makefile.config.override

