#
# NetSurf default build configuration
#
# This file is included after Makefile.defaults and can be used to
# provide local build configuration overrides.
#
# For example, by default, NetSurf builds with BMP support.  If you
# wish to disable this, then uncomment the following line.

# override NETSURF_USE_BMP := NO
