# Makefile for NetSurf's resources
#
# Copyright 2009 Daniel Silverstone <dsilvers@netsurf-browser.org>
#
#
# This file provides the rules and setup for built-in resources for
# the NetSurf browser binary.

ifeq ($(TARGET),framebuffer)


# End of framebuffer resource definitions
endif

ifeq ($(TARGET),windows)


# End of windows resource definitions
endif
