#
# NetSurf build configuration
#
# Some of these options support an 'AUTO' option, as well as YES and NO.  If
# AUTO is set, the Makefile will attempt to detect if that feature is available

# Use libharu to enable PDF export and GTK printing support.  There is no
# auto-detection available for this, as it does not have a pkg-config file.
NETSURF_USE_HARU_PDF=YES

# The following options are GTK-specific
ifeq ($(TARGET),gtk)

# Use librsvg in conjunction with Cairo to render SVG images
NETSURF_USE_RSVG=AUTO

# Use James Shaw's librosprite for rendering RISC OS Sprites
NETSURF_USE_ROSPRITE=AUTO

endif

