#!/bin/sh
# This file is part of NetSurf, http://netsurf-browser.org/
# Licensed under the GNU General Public License,
#                http://www.opensource.org/licenses/gpl-license
# Copyright 2007 Rob Kendrick <rjek@netsurf-browser.org>

if [ -d ~/.netsurf ]; then
  LOG=~/.netsurf/log.txt
elif [ -d /tmp ]; then
  LOG=/tmp/netsurf-log.txt
else
  LOG=netsurf-log.txt
fi

NETSURFRES=`dirname $0`/gtk/res/
export NETSURFRES
exec `dirname $0`/nsgtk "$@" 2>$LOG
