#!/bin/sh
# This file is part of NetSurf, http://netsurf-browser.org/
# Licensed under the GNU General Public License,
#                http://www.opensource.org/licenses/gpl-license
# Copyright 2007 Rob Kendrick <rjek@netsurf-browser.org>

if [ -d ~/.netsurf ]; then
  LOG=~/.netsurf/log.txt
elif [ -d /tmp ]; then
  LOG=/tmp/netsurf-log.txt
else
  LOG=netsurf-log.txt
fi

if [ -x nsfb-sdl ]; then
TYPE=-sdl
elif [ -x nsfb-linux ]; then
TYPE=-linux
elif [ -x nsfb-dummy ]; then
TYPE=-dummy
fi

NETSURFRES=$(dirname $0)/framebuffer/res/
export NETSURFRES
exec $(dirname $0)/nsfb${TYPE} "$@" 2>$LOG
