# about fetcher sources

S_FETCHER_ABOUT := \
	about.c \
	blank.c \
	certificate.c \
	config.c \
	imagecache.c \
	testament.c

# The following files depend on the testament
content/fetchers/about/testament.c: testament $(OBJROOT)/testament.h
