# -*- mode: makefile-gmake -*-
##
## tool setup for the gtk target
##

# use native package config
PKG_CONFIG := pkg-config

# gtk target processing
ifeq ($(SUBTARGET),3)
  override NETSURF_GTK_MAJOR := 3
endif

ifeq ($(SUBTARGET),2)
  override NETSURF_GTK_MAJOR := 2
endif
