# utils sources

S_UTILS := \
	bloom.c \
	corestrings.c \
	file.c \
	filename.c \
	filepath.c \
	hashtable.c \
	idna.c \
	libdom.c \
	log.c \
	messages.c \
	nsoption.c \
	punycode.c \
	talloc.c \
	time.c \
	url.c \
	useragent.c \
	utf8.c \
	utils.c

S_UTILS := $(addprefix utils/,$(S_UTILS))
