# HTML content handler sources

S_HTML := box.c box_construct.c box_normalise.c box_textarea.c	\
	font.c form.c imagemap.c layout.c search.c table.c 	\
	html.c html_css.c html_css_fetcher.c html_script.c	\
	html_interaction.c html_redraw.c html_redraw_border.c	\
	html_forms.c html_object.c
